version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./wp-data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: "${DB_NAME}"
       MYSQL_USER: "${DB_USER}"
       MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"
   wordpress:
     depends_on:
       - db
     build:
       args:
         WP_IMAGE: wordpress:latest # https://hub.docker.com/_/wordpress/
       context: ./docker/wordpress/
     ports:
       - "8000:80"
     restart: always
     volumes:
        - ./config/php.ini:/usr/local/etc/php/php.ini
        - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
        - ./wp-app:/var/www/html # Full wordpress project
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: "${DB_USER}"
       WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
       WORDPRESS_DB_NAME: "${DB_NAME}"
   wpcli:
     image: wordpress:cli
     volumes:
        - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
        - ./wp-app:/var/www/html
     depends_on:
        - db
        - wordpress
   pma:
      image: phpmyadmin/phpmyadmin
      environment:
        # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
        PMA_HOST: db
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      ports:
        - ${IP}:8080:80
      links:
        - db:db